version: 2

jobs:
  # Install packages.
  install:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package.json" }}
      - run:
          name: Fetch dependencies
          command: npm install
      - save_cache:
          key: node_modules-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ./
          paths:
            - ./
  # Run a script.
  run:
    docker:
      - image: circleci/node:lts
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Fetch dependencies
          command: node index.js

workflows:
  version: 2
  install-run:
    # triggers:
    #   - schedule:
    #       cron: "0 17 * * 3"
    jobs:
      - install
      - run
